"""Shared vocabulary for every system PayFlow reconciles."""

from enum import StrEnum


class PaymentState(StrEnum):
    CREATED = "CREATED"
    PROCESSING = "PROCESSING"
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"
    SETTLED = "SETTLED"
    REFUND_PENDING = "REFUND_PENDING"
    REFUNDED = "REFUNDED"


class GatewayStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING = "PENDING"
    TIMEOUT = "TIMEOUT"
    UNKNOWN = "UNKNOWN"
    REFUND_FAILED = "REFUND_FAILED"
    REFUNDED = "REFUNDED"


class BankStatus(StrEnum):
    SETTLED = "SETTLED"
    PENDING = "PENDING"
    FAILED = "FAILED"
    NOT_FOUND = "NOT_FOUND"
    REFUNDED = "REFUNDED"


class MerchantStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING = "PENDING"
    DUPLICATE = "DUPLICATE"
    REFUND_REQUESTED = "REFUND_REQUESTED"
    REFUNDED = "REFUNDED"


class LedgerStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING = "PENDING"
    REFUNDED = "REFUNDED"


class WebhookStatus(StrEnum):
    RECEIVED = "RECEIVED"
    DELAYED = "DELAYED"
    NOT_RECEIVED = "NOT_RECEIVED"
    AWAITING = "AWAITING"  # capture done, webhook expected within the grace period
    NOT_CONFIGURED = "NOT_CONFIGURED"  # PAYPAL_WEBHOOK_ID not set; API response is authoritative
    RESYNCED = "RESYNCED"  # missing webhook replaced by a PayPal API status pull


class Provider(StrEnum):
    PAYPAL_SANDBOX = "PAYPAL_SANDBOX"
    PAYFLOW_HISTORICAL = "PAYFLOW_HISTORICAL"
    SYNTHETIC = "SYNTHETIC"


class ReconciliationStatus(StrEnum):
    PENDING = "PENDING"
    MATCHED = "MATCHED"
    MISMATCH = "MISMATCH"


class FailureSource(StrEnum):
    PAYPAL_PROVIDER_FAILURE = "PAYPAL_PROVIDER_FAILURE"
    PAYFLOW_INFRASTRUCTURE_FAILURE = "PAYFLOW_INFRASTRUCTURE_FAILURE"
    HISTORICAL = "HISTORICAL"


class Scenario(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    PENDING = "PENDING"
    WEBHOOK_DELAY = "WEBHOOK_DELAY"
    WEBHOOK_LOST = "WEBHOOK_LOST"
    LEDGER_MISMATCH = "LEDGER_MISMATCH"
    SETTLEMENT_MISMATCH = "SETTLEMENT_MISMATCH"
    DUPLICATE_PAYMENT = "DUPLICATE_PAYMENT"
    REFUND_FAILURE = "REFUND_FAILURE"
    UNKNOWN_STATE = "UNKNOWN_STATE"


class IncidentType(StrEnum):
    LEDGER_MISMATCH = "LEDGER_MISMATCH"
    SETTLEMENT_MISMATCH = "SETTLEMENT_MISMATCH"
    WEBHOOK_DELAY = "WEBHOOK_DELAY"
    WEBHOOK_LOST = "WEBHOOK_LOST"
    DUPLICATE_PAYMENT = "DUPLICATE_PAYMENT"
    REFUND_FAILURE = "REFUND_FAILURE"
    GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"
    UNKNOWN_STATE = "UNKNOWN_STATE"
    PROVIDER_DECLINED = "PROVIDER_DECLINED"
    REFUND_REQUESTED = "REFUND_REQUESTED"


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus(StrEnum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    REMEDIATING = "REMEDIATING"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"
    CLOSED = "CLOSED"  # closed by a human as false positive / accepted


ACTIVE_INCIDENT_STATUSES = (
    IncidentStatus.OPEN,
    IncidentStatus.INVESTIGATING,
    IncidentStatus.AWAITING_APPROVAL,
    IncidentStatus.REMEDIATING,
    IncidentStatus.ESCALATED,
)


class ActionType(StrEnum):
    RECONCILE_LEDGER = "RECONCILE_LEDGER"
    RETRY_WEBHOOK = "RETRY_WEBHOOK"
    REFUND = "REFUND"
    MARK_PAYMENT_FAILED = "MARK_PAYMENT_FAILED"
    ESCALATE = "ESCALATE"


class ActionStatus(StrEnum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"


class PolicyDecision(StrEnum):
    ALLOW = "ALLOW"
    HUMAN_APPROVAL_REQUIRED = "HUMAN_APPROVAL_REQUIRED"
    DENY = "DENY"


class Risk(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class AuditEvent(StrEnum):
    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_EVENT_RECEIVED = "PAYMENT_EVENT_RECEIVED"
    MISMATCH_DETECTED = "MISMATCH_DETECTED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INVESTIGATION_STARTED = "INVESTIGATION_STARTED"
    HISTORICAL_MATCH_FOUND = "HISTORICAL_MATCH_FOUND"
    AI_RECOMMENDATION_CREATED = "AI_RECOMMENDATION_CREATED"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_REJECTED = "ACTION_REJECTED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    ACTION_FAILED = "ACTION_FAILED"
    ACTION_DEDUPLICATED = "ACTION_DEDUPLICATED"
    VERIFICATION_PASSED = "VERIFICATION_PASSED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
    INCIDENT_ESCALATED = "INCIDENT_ESCALATED"
    JOB_FAILED = "JOB_FAILED"
    NOTIFICATION_SENT = "NOTIFICATION_SENT"
    ACTION_CREATED = "ACTION_CREATED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_RETRY = "VERIFICATION_RETRY"
    # provider / webhook lifecycle
    PAYMENT_APPROVAL_STARTED = "PAYMENT_APPROVAL_STARTED"
    PAYMENT_APPROVED = "PAYMENT_APPROVED"
    PAYMENT_CAPTURE_STARTED = "PAYMENT_CAPTURE_STARTED"
    PAYMENT_CAPTURE_COMPLETED = "PAYMENT_CAPTURE_COMPLETED"
    PAYMENT_CAPTURE_FAILED = "PAYMENT_CAPTURE_FAILED"
    PROVIDER_CALL_FAILED = "PROVIDER_CALL_FAILED"
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    WEBHOOK_VERIFIED = "WEBHOOK_VERIFIED"
    WEBHOOK_REJECTED = "WEBHOOK_REJECTED"
    WEBHOOK_DUPLICATE = "WEBHOOK_DUPLICATE"
    WEBHOOK_DELAYED = "WEBHOOK_DELAYED"
    WEBHOOK_DROPPED = "WEBHOOK_DROPPED"
    DOWNSTREAM_UPDATED = "DOWNSTREAM_UPDATED"
    FAILURE_INJECTED = "FAILURE_INJECTED"
    REFUND_REQUESTED = "REFUND_REQUESTED"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED"
    AI_RECOMMENDATION_OVERRIDDEN = "AI_RECOMMENDATION_OVERRIDDEN"
    INCIDENT_ACKNOWLEDGED = "INCIDENT_ACKNOWLEDGED"
    INCIDENT_CLOSED = "INCIDENT_CLOSED"
    HUMAN_RETRY_REQUESTED = "HUMAN_RETRY_REQUESTED"
